runtime: java
env: flex
runtime_config:
  jdk: openjdk8

skip_files:
- .idea/
- build/
- out/
- *.iml

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  forwarded_ports:
    - 80/tcp

manual_scaling:
  instances: 1